name: NK Auto Reboot (AppVeyor Branch)

on:
  schedule:
    - cron: '*/50 * * * *' # 每 50 分钟自动跳动一次
  workflow_dispatch: # 允许你随时手动点按钮测试

jobs:
  reboot_task:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AppVeyor Build
        run: |
          curl -s -X POST "https://ci.appveyor.com/api/builds" \
            -H "Authorization: Bearer ${{ secrets.APPVEYOR_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
                  \"accountName\": \"baico\",
                  \"projectSlug\": \"nodejs-argo\",
                  \"branch\": \"appveyor\"
                }"
