name: NK Auto Reboot (AppVeyor Branch)

on:
  schedule:
    - cron: '*/50 * * * *'
  workflow_dispatch:

jobs:
  reboot_task:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AppVeyor
        run: |
          curl -v -X POST \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -d "{}" \
            "https://ci.appveyor.com/api/github/webhook?id=5dsrsoe1ub09t44f"
